### ISSUE TITLE
Can't work with "Remote - Containers extension"

### ISSUE THREAD

**Issue by ttsuru** [TheNouillet/symfony-vscode#45]
Thanks for developing this extention!

But can't work with "Remote - Containers extension"

Error message

```
[2019-10-14 17:13:43.676] [exthost] [error] [TheNouillet.symfony-vscode] provider FAILED
[2019-10-14 17:13:43.676] [exthost] [error] TypeError: Cannot read property 'find' of undefined
	at ServiceDocumentationCodeActionProvider.provideCodeActions (/root/.vscode-server/extensions/thenouillet.symfony-vscode-1.0.2/out/mvc/editing/codeaction/ServiceDocumentationCodeActionProvider.js:20:70)
	at o.asPromise (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:571:465)
	at Promise (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:55:649)
	at new Promise (<anonymous>)
	at Object.t.asPromise (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:55:621)
	at C.provideCodeActions (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:571:436)
	at _withAdapter.e (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:587:817)
	at H._withAdapter (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:583:593)
	at H.$provideCodeActions (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:587:795)
	at p._doInvokeHandler (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:652:275)
	at p._invokeHandler (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:651:971)
	at p._receiveRequest (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:650:588)
	at p._receiveOneMessage (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:649:468)
	at _protocol.onMessage.e (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:647:691)
	at l.fire (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:50:519)
	at _.fire (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:181:274)
	at e.onMessage.e (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:804:104)
	at l.fire (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:50:519)
	at _.fire (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:181:274)
	at t.PersistentProtocol._receiveMessage (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:185:629)
	at _socketDisposables.push._socketReader.onMessage.e (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:182:824)
	at l.fire (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:50:519)
	at p.acceptChunk (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:178:588)
	at _register._socket.onData.e (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:177:958)
	at Socket.t (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:187:68)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Do you have any solutions?

**Comment by ttsuru** [comment]
And cause other error

```
[2019-10-14 21:42:26.241] [exthost] [error] [TheNouillet.symfony-vscode] provider FAILED
[2019-10-14 21:42:26.268] [exthost] [error] Error: Illegal argument: character must be non-negative
	at Object.t.illegalArgument (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:13:524)
	at new p (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:361:76)
	at new p (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:360:392)
	at translate (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:362:351)
	at Function.getWordRange (/root/.vscode-server/extensions/thenouillet.symfony-vscode-1.0.2/out/mvc/editing/EditingUtils.js:8:64)
	at ServiceDocumentationCodeActionProvider.provideCodeActions (/root/.vscode-server/extensions/thenouillet.symfony-vscode-1.0.2/out/mvc/editing/codeaction/ServiceDocumentationCodeActionProvider.js:18:69)
	at o.asPromise (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:571:465)
	at Promise (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:55:649)
	at new Promise (<anonymous>)
	at Object.t.asPromise (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:55:621)
	at C.provideCodeActions (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:571:436)
	at _withAdapter.e (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:587:817)
	at H._withAdapter (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:583:593)
	at H.$provideCodeActions (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:587:795)
	at p._doInvokeHandler (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:652:275)
	at p._invokeHandler (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:651:971)
	at p._receiveRequest (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:650:588)
	at p._receiveOneMessage (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:649:468)
	at _protocol.onMessage.e (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:647:691)
	at l.fire (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:50:519)
	at _.fire (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:181:274)
	at e.onMessage.e (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:804:104)
	at l.fire (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:50:519)
	at _.fire (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:181:274)
	at t.PersistentProtocol._receiveMessage (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:185:629)
	at _socketDisposables.push._socketReader.onMessage.e (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:182:824)
	at l.fire (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:50:519)
	at p.acceptChunk (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:178:588)
	at _register._socket.onData.e (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:177:958)
	at Socket.t (/root/.vscode-server/bin/88f15d17dca836346e787762685a40bb5cce75a8/out/vs/server/remoteExtensionHostProcess.js:187:68)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by serk7** [comment]
same problem here

**Comment by davidhaley** [comment]
Same error, except for node extension.

```
[2020-01-15 10:30:32.552] [renderer4] [error] Cannot read property 'find' of undefined: TypeError: Cannot read property 'find' of undefined
	at ServiceDocumentationCodeActionProvider.provideCodeActions (/home/dh/.vscode/extensions/thenouillet.symfony-vscode-1.0.2/out/mvc/editing/codeaction/ServiceDocumentationCodeActionProvider.js:20:70)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:576:562
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:287
	at new Promise (<anonymous>)
	at Object.t.asPromise (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:259)
	at P.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:576:533)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:595:972
	at B._withAdapter (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:591:697)
	at B.$provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:595:950)
	at p._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:663:275)
	at p._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:662:971)
	at p._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:661:588)
	at p._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:660:468)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:658:691
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:820:285
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at _.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)
	at t.PersistentProtocol._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:193:629)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:190:824
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)
	at p.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:737)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:89
	at Socket.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:195:68)
	at Socket.emit (events.js:200:13)
	at addChunk (_stream_readable.js:294:12)
	at readableAddChunk (_stream_readable.js:275:11)
	at Socket.Readable.push (_stream_readable.js:210:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by armellin** [comment]
Same error with "Remote - Containers extension"
